parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

env:
  node: true
  browser: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  no-console: 0
  react/props-types: 0
  react/display-name: 0
